#include "stm32f4xx_hal.h"

// Define LCD Pins
#define LCD_DATA_PORT GPIOC  // Data lines (D4-D7) connected to PC4-PC7
#define RS_PIN GPIO_PIN_5    // Register Select (PB5)
#define RW_PIN GPIO_PIN_6    // Read/Write (PB6) - Always LOW
#define EN_PIN GPIO_PIN_7    // Enable (PB7)
#define LCD_CTRL_PORT GPIOB  // Control port (RS, RW, EN)

// Function prototypes
void LCD_Command(uint8_t cmd);
void LCD_Char(char data);
void LCD_Init(void);
void LCD_String(char *str);
void LCD_EnablePulse(void);
void LCD_Send4Bits(uint8_t data);
void SystemClock_Config(void);
static void MX_GPIO_Init(void);

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    LCD_Init();

    LCD_String("Hello, STM32!");

    while (1) {}
}

// Send command to LCD (4-bit mode)
void LCD_Command(uint8_t cmd)
{
    HAL_GPIO_WritePin(LCD_CTRL_PORT, RS_PIN, GPIO_PIN_RESET); // RS = 0 (Command mode)
    HAL_GPIO_WritePin(LCD_CTRL_PORT, RW_PIN, GPIO_PIN_RESET); // RW = 0 (Write mode)
    LCD_Send4Bits(cmd >> 4); // Send upper 4 bits
    LCD_Send4Bits(cmd & 0x0F); // Send lower 4 bits
}

// Send character to LCD (4-bit mode)
void LCD_Char(char data)
{
    HAL_GPIO_WritePin(LCD_CTRL_PORT, RS_PIN, GPIO_PIN_SET);  // RS = 1 (Data mode)
    HAL_GPIO_WritePin(LCD_CTRL_PORT, RW_PIN, GPIO_PIN_RESET); // RW = 0 (Write mode)
    LCD_Send4Bits(data >> 4); // Send upper 4 bits
    LCD_Send4Bits(data & 0x0F); // Send lower 4 bits
}

// Send string to LCD
void LCD_String(char *str)
{
    while (*str)
    {
        LCD_Char(*str++);
    }
}

// Send 4-bit data to LCD
void LCD_Send4Bits(uint8_t data)
{
    HAL_GPIO_WritePin(LCD_DATA_PORT, 0xF0, GPIO_PIN_RESET); // Clear D4-D7
    HAL_GPIO_WritePin(LCD_DATA_PORT, (data << 4), GPIO_PIN_SET); // Send bits to D4-D7
    LCD_EnablePulse();
}

// Generate enable pulse
void LCD_EnablePulse(void)
{
    HAL_GPIO_WritePin(LCD_CTRL_PORT, EN_PIN, GPIO_PIN_SET);
    HAL_Delay(1);
    HAL_GPIO_WritePin(LCD_CTRL_PORT, EN_PIN, GPIO_PIN_RESET);
    HAL_Delay(1);
}

// Initialize LCD in 4-bit mode
void LCD_Init(void)
{
    HAL_Delay(50);

    // Initialize in 4-bit mode (special sequence)
    LCD_Send4Bits(0x03); // Send 3 three times to force 4-bit mode
    HAL_Delay(5);
    LCD_Send4Bits(0x03);
    HAL_Delay(1);
    LCD_Send4Bits(0x03);
    HAL_Delay(1);
    LCD_Send4Bits(0x02); // Switch to 4-bit mode

    // Configure LCD
    LCD_Command(0x28); // 4-bit mode, 2-line, 5x7 font
    LCD_Command(0x0C); // Display ON, Cursor OFF
    LCD_Command(0x06); // Auto increment cursor
    LCD_Command(0x01); // Clear display
    HAL_Delay(5);
}

// Initialize GPIO
static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    GPIO_InitTypeDef GPIO_InitStruct = {0};

    // LCD Data Pins (D4-D7) on PC4-PC7
    GPIO_InitStruct.Pin = GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(LCD_DATA_PORT, &GPIO_InitStruct);

    // Control Pins (RS, RW, EN) on PB5, PB6, PB7
    GPIO_InitStruct.Pin = RS_PIN | RW_PIN | EN_PIN;
    HAL_GPIO_Init(LCD_CTRL_PORT, &GPIO_InitStruct);
}

// System Clock Configuration
void SystemClock_Config(void)
{
    // System clock configuration function (Generated by CubeMX)
}
