#include "stm32f4xx_hal.h"

void SystemClock_Config(void);
static void MX_GPIO_Init(void);

volatile uint8_t led_state = 0; // Stores LED state (0 = OFF, 1 = ON)

int main(void) {
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();

    while (1) {
        // Main loop does nothing; LED toggling is handled in the interrupt
    }
}

// GPIO Initialization
static void MX_GPIO_Init(void) {
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();

    GPIO_InitTypeDef GPIO_InitStruct = {0};

    // Configure PA8 as output (LED)
    GPIO_InitStruct.Pin = GPIO_PIN_8;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    // Configure PC9 as input with external interrupt
    GPIO_InitStruct.Pin = GPIO_PIN_9;
    GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING; // Trigger on button press
    GPIO_InitStruct.Pull = GPIO_PULLUP; // Enable pull-up resistor
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);

    // Enable EXTI interrupt for PC9
    HAL_NVIC_SetPriority(EXTI9_5_IRQn, 2, 0);
    HAL_NVIC_EnableIRQ(EXTI9_5_IRQn);
}

// Interrupt callback function
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin) {
    if (GPIO_Pin == GPIO_PIN_9) {
        led_state = !led_state; // Toggle LED state
        HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, led_state ? GPIO_PIN_SET : GPIO_PIN_RESET);
    }
}

// EXTI IRQ Handler
void EXTI9_5_IRQHandler(void) {
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_9);
}

// System clock configuration (adjust if necessary)
void SystemClock_Config(void) {
    // This function should be generated by STM32CubeMX
}
